#!/usr/bin/env bash
# The APT_PACKAGES install path: what reaches apt-get, and what does not.
#
# Two stages guard it. An anchored grammar rejects anything that is not
# name-shaped, then a known-name gate (apt-cache pkgnames) refuses anything that
# is not a real package -- and that second gate is what keeps a token away from
# apt's regex fallback, where `apt-get install -s -- 'jq.'` plans 337 packages.
# When the gate cannot run (a failed apt-get update, an unreadable index) the
# install still proceeds on the grammar alone, minus DOTTED tokens: '.' is the only
# apt metacharacter the grammar admits, so dropping just those removes the blowup
# while every plain name still installs.
#
# Drives the real inline block with apt stubbed, recording exactly what argv
# apt-get install would have received.
# Lint directives for this whole file, each against a stated guarantee rather than
# an assumption:
#   SC2015 - the assertion form `[ cond ] && ok "..." || no "..."` cannot mis-fire,
#     because lib.sh's ok/no return 0 unconditionally by design (see their comment).
#   SC2034 - the variables set below are the INPUTS to entrypoint.sh code that is
#     extracted and sourced at RUNTIME, so shellcheck cannot see the reads.
#   SC2016 - the grep patterns below must stay single-quoted: they match the
#     LITERAL "${APT_PACKAGES:-}" text in entrypoint.sh, not its expansion.
#   SC1091 - the sourced files are GENERATED by the extraction above.
# shellcheck disable=SC2015,SC2034,SC2016,SC1091
set -u

# shellcheck source-path=SCRIPTDIR
. "$(dirname -- "$0")/lib.sh"
new_workdir >/dev/null

# The logic under test is INLINE boot code, not a function, so it is taken by line
# range: from the APT_PACKAGES guard to the index reclaim, plus two lines to close
# the enclosing if. Line numbers are resolved from the file rather than hardcoded.
start=$(grep -n '^if \[ -n "${APT_PACKAGES:-}" \]; then$' "$ENTRYPOINT" | head -1 | cut -d: -f1)
end=$(grep -n 'rm -rf /var/lib/apt/lists/\*' "$ENTRYPOINT" | head -1 | cut -d: -f1)
if [ -z "$start" ] || [ -z "$end" ]; then
  printf 'harness error: could not locate the APT_PACKAGES block (start=%s end=%s)\n' \
    "$start" "$end" >&2
  exit 1
fi
sed -n "${start},$((end + 2))p" "$ENTRYPOINT" >"$WORK/block.sh"
extract_function warn_skipped_apt_token "$WORK/warn.sh" >/dev/null

# RUN_CWD lets a case choose the directory the harness runs FROM. Empty means "here":
# only the glob-suppression case below needs a controlled cwd, since that guard's
# bait is a directory whose FILENAMES are what an unsuppressed '*' would expand to.
RUN_CWD=""

# run <update_rc> <pkgnames_mode> <APT_PACKAGES>
#   pkgnames_mode: ok | empty | fail
# -> INSTALLED (the argv apt-get install received), SKIPPED (warn count)
run() {
  local urc=$1 mode=$2 pkgs=$3
  cat >"$WORK/harness.sh" <<HARNESS
set -u
APT_PACKAGES='$pkgs'
_URC=$urc
_MODE=$mode
apt-get() {
  case "\$*" in
    *update*) return \$_URC ;;
    *install*)
      # Record the CALL itself before any argv filtering: the empty-list guard is
      # asserted on invocations, and a stub that only records package args cannot
      # see an empty install.
      printf 'install-call\n' >>"$WORK/calls"
      # Then record exactly what apt would have been handed AS PACKAGES: everything
      # after the -- separator, verbatim. apt's own invocation options sit before
      # the separator and are not evidence; a hostile token shaped like an option
      # can only be a package, so it lands after -- and is recorded ('opt:'
      # prefixed) instead of vanishing into a filter.
      _sep=0
      for a in "\$@"; do
        case "\$a" in
          --) _sep=1; continue ;;
        esac
        [ "\$_sep" -eq 1 ] || continue
        case "\$a" in
          -*) printf 'opt:%s\n' "\$a" >>"$WORK/installed" ;;
          *) printf '%s\n' "\$a" >>"$WORK/installed" ;;
        esac
      done
      return 0 ;;
  esac
  return 0
}
apt-cache() {
  case "\$_MODE" in
    ok)    printf '%s\n' jq gcc python3 python3.13 docker.io g++ ;;
    empty) : ;;
    fail)  return 1 ;;
  esac
}
timeout() { shift 3; "\$@"; }
rm() {
  # The extracted block ends with the index reclaim (\`rm -rf /var/lib/apt/lists/*\`).
  # apt-get is stubbed here; rm is NOT, so that line is real: run as root -- the
  # ordinary way inside this container -- the suite wipes the package index and the
  # next apt-get install fails until an update. Intercept exactly that path (and
  # record it, so the reclaim stays observable) while every other rm still runs.
  case "\$*" in
    */var/lib/apt/lists/*)
      printf 'apt-lists-reclaim\n' >>"$WORK/calls"
      return 0
      ;;
  esac
  command rm "\$@"
}
$(cat "$WORK/warn.sh")
$(cat "$WORK/block.sh")
HARNESS
  : >"$WORK/installed"
  : >"$WORK/calls"
  SKIPPED=$(cd "${RUN_CWD:-$PWD}" && bash "$WORK/harness.sh" 2>&1 >/dev/null | grep -c 'level=warn.*skipping' || true)
  INSTALLED=$(tr '\n' ' ' <"$WORK/installed" | sed 's/ *$//')
  INSTALL_CALLS=$(grep -c 'install-call' "$WORK/calls" 2>/dev/null || true)
}

# --- the gate RUNS: unchanged behaviour, dots verified literally -------------
run 0 ok 'jq python3.13 docker.io nosuchpkg.'
[ "$INSTALLED" = "jq python3.13 docker.io" ] \
  && ok "gate available: real dotted names install, the typo is rejected" \
  || no "gate available" "installed='$INSTALLED', want 'jq python3.13 docker.io'"

# --- THE REGRESSION: gate unavailable via a failed update --------------------
run 100 ok 'jq gcc python3.13 nosuchpkg.'
case "$INSTALLED" in
  *nosuchpkg.*) no "update failed" "'nosuchpkg.' reached apt -- the 337-package regex blowup is live" ;;
  *)
    [ "$INSTALLED" = "jq gcc" ] \
      && ok "update failed: plain names install, every dotted token dropped" \
      || no "update failed" "installed='$INSTALLED', want 'jq gcc'"
    ;;
esac

# --- gate unavailable via an unreadable index -------------------------------
for mode in empty fail; do
  run 0 "$mode" 'jq gcc python3.13 nosuchpkg.'
  [ "$INSTALLED" = "jq gcc" ] \
    && ok "index $mode: plain names install, every dotted token dropped" \
    || no "index $mode" "installed='$INSTALLED', want 'jq gcc'"
done

# --- the common case must not regress: no dots, nothing to drop --------------
run 100 ok 'jq gcc g++'
[ "$INSTALLED" = "jq gcc g++" ] && [ "$SKIPPED" -eq 0 ] \
  && ok "no dotted tokens: a degraded boot installs everything, silently" \
  || no "undotted degraded" "installed='$INSTALLED' skipped=$SKIPPED"

# --- an all-dotted list must not invoke apt with an empty argv ---------------
# INSTALL_CALLS is the oracle, not the package list: an empty install records no
# packages either way, so only the invocation count can see this guard.
run 100 ok 'python3.13 docker.io'
[ "$INSTALL_CALLS" -eq 0 ] && [ -z "$INSTALLED" ] && [ "$SKIPPED" -eq 2 ] \
  && ok "all tokens dropped: apt is not called with an empty package list" \
  || no "all dropped" "install_calls=$INSTALL_CALLS installed='$INSTALLED' skipped=$SKIPPED"

# --- the grammar stage still owns its own rejections ------------------------
# Run with the GATE UNAVAILABLE (failed update): with the gate up, these tokens
# would be rejected by the known-name check too, and this case could go green with
# the grammar deleted. Degraded mode is where only the grammar stands between a
# hostile token and apt's argv, so that is where it is asserted. 'jq-' is the
# canary: name-shaped enough to reach apt if the grammar's anchor broke, absent
# from the known-name list, and not dotted (so the degraded dotted-token drop
# cannot mask its rejection either).
# `etc/passwd` carries no dot either, so the degraded dotted-token drop cannot mask
# it: it is the traversal/slash canary the way `jq-` is the anchor canary, and it
# isolates the grammar's slash rejection that `../etc/passwd` alone cannot.
# `../etc/passwd` stays for the dotted-traversal shape.
run 100 ok 'jq ../etc/passwd etc/passwd jq- -0day'
case "$INSTALLED" in
  *jq-* | *passwd* | *opt:*) no "grammar" "a grammar-invalid token reached apt: '$INSTALLED'" ;;
  *)
    [ "$INSTALLED" = "jq" ] \
      && ok "grammar rejections hold with the gate down (traversal, remove-suffix, option-like)" \
      || no "grammar" "installed='$INSTALLED', want 'jq'"
    ;;
esac

# --- the glob-suppression guard: a stray '*' must stay LITERAL ----------------
# entrypoint.sh runs with cwd=/workspace, so with pathname expansion live a '*'
# token expands to filenames and any expansion that is grammar-valid AND a real
# package gets apt-installed as root on every boot. The bait is what the UNGUARDED
# code would actually take: a cwd holding a file named like a package the
# known-name stub accepts. With `set -f` present the token stays literal, fails the
# grammar (no '*' in its class) and is warn-skipped; with `set -f` gone this case
# reports installed='jq gcc'.
# The bait filename stays inside the stub's known-name list (`gcc`) so the assertion
# fails at the INSTALL argv rather than being masked by the known-name gate, and
# stays undotted so the degraded-path dotted-token drop cannot mask it either -- the
# same canary discipline the grammar case documents for `jq-` and `etc/passwd`.
mkdir -p "$WORK/globbait" && : >"$WORK/globbait/gcc"
RUN_CWD="$WORK/globbait"
run 0 ok 'jq *'
RUN_CWD=""
[ "$INSTALLED" = "jq" ] && [ "$SKIPPED" -eq 1 ] \
  && ok "a stray '*' stays literal (set -f) and is warn-skipped" \
  || no "glob suppression" "installed='$INSTALLED' skipped=$SKIPPED -- set -f may be gone"

report
