#!/usr/bin/env bash
# The kiro-cli update transaction: download and verify BEFORE deleting anything,
# and if the update fails, keep serving the version already on the volume.
#
# This is the app's availability trade, made deliberately: this container IS the
# operator's access path, so a working old terminal beats a dead one, and the pin
# is advisory while an update keeps failing. That makes the fallback's exact shape
# load-bearing — readiness must still be published, with a warn naming pinned vs
# running, and it must be WITHHELD in the one case where the terminal would be
# unsafe rather than merely stale (auto-update could not be disabled, so the binary
# could silently replace itself and invalidate the pinned sha).
#
# Extracts the two helpers whose return codes the decision reads, plus the real
# readiness chain, and drives them with stubs for the two things that would
# otherwise spawn a process or touch the host.
# Lint directives for this whole file, each against a stated guarantee rather than
# an assumption:
#   SC2015 - the assertion form `[ cond ] && ok "..." || no "..."` cannot mis-fire,
#     because lib.sh's ok/no return 0 unconditionally by design (see their comment).
#   SC2034 - the variables set below are the INPUTS to entrypoint.sh code that is
#     extracted and sourced at RUNTIME, so shellcheck cannot see the reads.
#   SC1091 - the sourced files are GENERATED by the extraction above, so there is
#     nothing on disk for shellcheck to follow at lint time.
# shellcheck disable=SC2015,SC2034,SC1091
set -u

# shellcheck source-path=SCRIPTDIR
. "$(dirname -- "$0")/lib.sh"
new_workdir >/dev/null

# The two helpers whose return codes the fix depends on, concatenated into one
# sourceable file.
HELPERS="$WORK/helpers.sh"
extract_function kiro_cli_dispatcher_set_complete "$HELPERS" >/dev/null
extract_function resolves_to_pinned_kiro_cli "$WORK/_resolve.sh" >/dev/null
cat "$WORK/_resolve.sh" >>"$HELPERS"
# The update transaction: the journal is what keeps an interrupted promotion from
# leaving the OLD $BIN paired with the NEW chat sidecar.
for _fn in is_self_contained_executable kiro_cli_snapshot_one kiro_cli_restore_one \
  kiro_cli_update_finish kiro_cli_update_begin kiro_cli_update_rollback \
  recover_kiro_cli_update_journal publish_readiness_marker; do
  extract_function "$_fn" "$WORK/_$_fn.sh" >/dev/null
  cat "$WORK/_$_fn.sh" >>"$HELPERS"
done
# The readiness decision chain is inline boot code, not a function: take it from
# the version probe down to the line before the next section, then drop that line.
READINESS=$(extract_range '^kiro_cli_installed=""' '^# OS packages' "$WORK/readiness.raw") || exit 1
sed '$d' "$READINESS" >"$WORK/readiness.sh"

# --- scenario scaffolding -----------------------------------------------------
# Each scenario gets a fresh fake volume. Stubs stand in for the two things that
# would otherwise spawn processes or touch the host: the shape test and --version.
setup() {
  ROOT=$(mktemp -d "$WORK/vol.XXXXXX")
  TOOLS="$ROOT/tools"
  HOME="$ROOT/home"
  mkdir -p "$TOOLS/bin" "$HOME/.local/bin"
  BIN="$TOOLS/bin/kiro-cli"
  CHAT_SIDECAR="$TOOLS/bin/kiro-cli-chat"
  KIRO_CLI_INSTALL_MARKER="$TOOLS/.kiro-cli-installed"
  KIRO_CLI_READY_MARKER="$TOOLS/.kiro-cli-ready"
  KIRO_CLI_UPDATE_JOURNAL="$TOOLS/.kiro-cli-update-in-progress"
  BIN_PREV="$TOOLS/bin/.kiro-cli.prev"
  CHAT_SIDECAR_PREV="$TOOLS/bin/.kiro-cli-chat.prev"
  KIRO_CLI_INSTALL_MARKER_PREV="$TOOLS/.kiro-cli-installed.prev"
  KIRO_CLI_VERSION="2.14.1"
  SESSION_PATH="$TOOLS/bin:$HOME/.local/bin:/usr/bin"
  kiro_cli_pin_enforced=1
  kiro_cli_update_failed=0
  STUB_VERSION=""
  FATALS=""
}
kiro_cli_version() {
  [ -n "$STUB_VERSION" ] || return 1
  printf '%s\n' "$STUB_VERSION"
}
fatal() { FATALS="$FATALS|$1"; }
# The readiness range now opens with the KAS prune (it runs once the version that will
# actually run is known). Its own behavior is kas_prune_test.sh's subject, and it would
# reach outside the fake volume here, so stub it out to a no-op.
prune_superseded_kas_runtimes() { :; }

ready_published() {
  rm -f "$KIRO_CLI_READY_MARKER"
  # shellcheck disable=SC1090  # extracted chain, path is computed
  . "$WORK/readiness.sh" >/dev/null 2>&1
  [ -f "$KIRO_CLI_READY_MARKER" ]
}

# shellcheck disable=SC1090
. "$WORK/helpers.sh"

# --- 1. dispatcher_set_complete return-code contract -------------------------
setup
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
printf '%s\n' "$KIRO_CLI_VERSION" >"$KIRO_CLI_INSTALL_MARKER"
kiro_cli_dispatcher_set_complete >/dev/null 2>&1
[ $? -eq 0 ] && ok "set_complete rc0 when sidecar ok + marker at pin" \
  || no "set_complete rc0" "expected 0"

setup
mkdir -p "$TOOLS/bin"
printf '%s\n' "$KIRO_CLI_VERSION" >"$KIRO_CLI_INSTALL_MARKER"
kiro_cli_dispatcher_set_complete >/dev/null 2>&1
set_rc=$?
[ "$set_rc" -eq 1 ] && ok "set_complete rc1 when the chat sidecar is missing (terminal broken)" \
  || no "set_complete rc1" "expected 1, got $set_rc"

setup
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
kiro_cli_dispatcher_set_complete >/dev/null 2>&1
[ $? -eq 2 ] && ok "set_complete rc2 when the marker is absent (pre-marker volume)" \
  || no "set_complete rc2 absent marker" "expected 2"

setup
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
printf '2.13.0\n' >"$KIRO_CLI_INSTALL_MARKER"
kiro_cli_dispatcher_set_complete >/dev/null 2>&1
[ $? -eq 2 ] && ok "set_complete rc2 when the marker names an older pin" \
  || no "set_complete rc2 old marker" "expected 2"

# --- 2. resolves_to_pinned_kiro_cli return-code contract ---------------------
setup
: >"$BIN" && chmod +x "$BIN"
STUB_VERSION="$KIRO_CLI_VERSION"
resolves_to_pinned_kiro_cli >/dev/null 2>&1
[ $? -eq 0 ] && ok "resolves rc0 when \$BIN is at the pin" || no "resolves rc0" "expected 0"

setup
: >"$BIN" && chmod +x "$BIN"
STUB_VERSION="2.13.0"
resolves_to_pinned_kiro_cli >/dev/null 2>&1
[ $? -eq 2 ] && ok "resolves rc2 when \$BIN holds an older version (the fallback state)" \
  || no "resolves rc2" "expected 2 -- the failed-update fallback would abort boot"

setup
: >"$HOME/.local/bin/kiro-cli" && chmod +x "$HOME/.local/bin/kiro-cli"
SESSION_PATH="$HOME/.local/bin:$TOOLS/bin:/usr/bin"
STUB_VERSION="2.13.0"
resolves_to_pinned_kiro_cli >/dev/null 2>&1
[ $? -eq 1 ] && ok "resolves rc1 when an unpinned copy elsewhere shadows \$BIN" \
  || no "resolves rc1" "expected 1 -- real shadowing must stay fatal"

setup
resolves_to_pinned_kiro_cli >/dev/null 2>&1
[ $? -eq 0 ] && ok "resolves rc0 when nothing is reachable at all" || no "resolves nothing" "expected 0"

# --- 3. readiness decision under each boot outcome --------------------------
# Happy path: install succeeded, everything at the pin.
setup
: >"$BIN" && chmod +x "$BIN"
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
printf '%s\n' "$KIRO_CLI_VERSION" >"$KIRO_CLI_INSTALL_MARKER"
STUB_VERSION="$KIRO_CLI_VERSION"
ready_published && ok "readiness PUBLISHED on a clean install" || no "clean install" "marker withheld"

# Failed update, older version still installed -> serve it.
setup
: >"$BIN" && chmod +x "$BIN"
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
printf '2.13.0\n' >"$KIRO_CLI_INSTALL_MARKER"
STUB_VERSION="2.13.0"
kiro_cli_update_failed=1
ready_published && ok "readiness PUBLISHED on a failed update with the old version present" \
  || no "failed update fallback" "marker withheld -- container would 503 over a working terminal"

# Failed update, nothing installed -> withhold.
setup
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
STUB_VERSION=""
kiro_cli_update_failed=1
ready_published && no "failed install, no binary" "marker published over a dead terminal" \
  || ok "readiness WITHHELD on a failed install with no binary at all"

# Pre-marker volume already at the pin, update failed -> serve it.
setup
: >"$BIN" && chmod +x "$BIN"
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
STUB_VERSION="$KIRO_CLI_VERSION"
kiro_cli_update_failed=1
ready_published && ok "readiness PUBLISHED on a pre-marker volume at the pin after a failed update" \
  || no "pre-marker volume" "marker withheld -- the exact regression this fix targets"

# Failed update, chat sidecar unusable -> withhold even though update_failed is set.
setup
: >"$BIN" && chmod +x "$BIN"
printf '%s\n' "$KIRO_CLI_VERSION" >"$KIRO_CLI_INSTALL_MARKER"
STUB_VERSION="$KIRO_CLI_VERSION"
kiro_cli_update_failed=1
ready_published && no "failed update, sidecar missing" "marker published but kiro-cli chat cannot dispatch" \
  || ok "readiness WITHHELD when the chat sidecar is unusable, fallback or not"

# Same rule on the OLD-VERSION fallback branch, which used to consult only "is $BIN
# executable": an interrupted update can leave the old $BIN beside a replaced sidecar,
# so an executable main dispatcher is not evidence that the terminal works.
setup
: >"$BIN" && chmod +x "$BIN"
printf '2.13.0\n' >"$KIRO_CLI_INSTALL_MARKER"
STUB_VERSION="2.13.0"
kiro_cli_update_failed=1
ready_published && no "failed update, old version, sidecar missing" \
  "marker published over an old \$BIN whose chat sidecar cannot dispatch" \
  || ok "readiness WITHHELD on the old-version fallback when the chat sidecar is unusable"

# A DOUBLE fault -- the update failed AND kiro_cli_update_rollback also failed -- is
# the one state that leaves the journal OPEN, and it is the one state where an
# executable $BIN plus a usable sidecar is still not evidence of a verified set: the
# old $BIN can sit beside an already-promoted NEW sidecar, which set_complete
# deliberately never version-probes. Both fallback branches must refuse to publish
# over it; the next boot's recovery pass repairs the set and publishes then.
setup
: >"$BIN" && chmod +x "$BIN"
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
printf '2.13.0\n' >"$KIRO_CLI_INSTALL_MARKER"
STUB_VERSION="2.13.0"
kiro_cli_update_failed=1
: >"$KIRO_CLI_UPDATE_JOURNAL"
ready_published && no "failed update, old version, open journal" \
  "marker published over a mixed set whose rollback never completed" \
  || ok "readiness WITHHELD on the old-version fallback while the update journal is open"

setup
: >"$BIN" && chmod +x "$BIN"
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
STUB_VERSION="$KIRO_CLI_VERSION"
kiro_cli_update_failed=1
: >"$KIRO_CLI_UPDATE_JOURNAL"
ready_published && no "pre-marker volume, open journal" \
  "marker published over a mixed set whose rollback never completed" \
  || ok "readiness WITHHELD on the pre-marker fallback while the update journal is open"

# Auto-update could not be disabled -> withhold (unchanged behaviour).
setup
: >"$BIN" && chmod +x "$BIN"
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
printf '%s\n' "$KIRO_CLI_VERSION" >"$KIRO_CLI_INSTALL_MARKER"
STUB_VERSION="$KIRO_CLI_VERSION"
kiro_cli_pin_enforced=0
ready_published && no "pin not enforced" "marker published though the binary may self-replace" \
  || ok "readiness WITHHELD when auto-update could not be disabled"

# --- 4. the update transaction ----------------------------------------------
# Plants a complete OLD set, opens the journal, then promotes ONLY the sidecar --
# exactly the mixed state a kill between the two renames leaves behind.
plant_old_set() {
  setup
  printf 'old-bin\n' >"$BIN" && chmod +x "$BIN"
  printf 'old-chat\n' >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
  printf '2.13.0\n' >"$KIRO_CLI_INSTALL_MARKER"
}
# Promotion is a RENAME in production, and the test must mimic that rather than
# writing in place: the backup is a hard link, so an in-place `>` would rewrite the
# shared inode and silently defeat it. `mv -f` replaces the directory entry only.
promote() {
  printf '%s\n' "$2" >"$WORK/promote.tmp" && chmod +x "$WORK/promote.tmp"
  mv -f "$WORK/promote.tmp" "$1"
}

plant_old_set
kiro_cli_update_begin >/dev/null 2>&1
[ -f "$KIRO_CLI_UPDATE_JOURNAL" ] && [ -f "$BIN_PREV" ] && [ -f "$CHAT_SIDECAR_PREV" ] \
  && ok "update_begin opens the journal and backs up the whole set" \
  || no "update_begin" "journal or a backup is missing"

plant_old_set
kiro_cli_update_begin >/dev/null 2>&1
promote "$CHAT_SIDECAR" new-chat
kiro_cli_update_rollback >/dev/null 2>&1
[ "$(cat "$CHAT_SIDECAR")" = "old-chat" ] && [ "$(cat "$BIN")" = "old-bin" ] \
  && ok "rollback restores the COMPLETE old set after a partial promotion" \
  || no "rollback" "the set stayed mixed: bin=$(cat "$BIN") chat=$(cat "$CHAT_SIDECAR")"

plant_old_set
kiro_cli_update_begin >/dev/null 2>&1
promote "$CHAT_SIDECAR" new-chat
kiro_cli_update_rollback >/dev/null 2>&1
[ ! -e "$KIRO_CLI_UPDATE_JOURNAL" ] && [ ! -e "$BIN_PREV" ] && [ ! -e "$CHAT_SIDECAR_PREV" ] \
  && ok "rollback closes the journal and drops its backups" \
  || no "rollback cleanup" "journal or backup residue survived"

# The REPAIR-install shape, which needs no kill at all: an old $BIN whose chat
# sidecar and completion marker are ABSENT. There is nothing to link aside for those
# two, so a rollback that could only restore backups left the promoted NEW sidecar
# and marker beside the restored OLD $BIN -- the same mixed set the journal exists to
# prevent. The `.absent` tombstones make the absence a snapshotted state, so rollback
# removes what this update promoted instead of adopting it.
setup
printf 'old-bin\n' >"$BIN" && chmod +x "$BIN"
kiro_cli_update_begin >/dev/null 2>&1
promote "$CHAT_SIDECAR" new-chat
promote "$KIRO_CLI_INSTALL_MARKER" "$KIRO_CLI_VERSION"
kiro_cli_update_rollback >/dev/null 2>&1
[ "$(cat "$BIN")" = "old-bin" ] && [ ! -e "$CHAT_SIDECAR" ] && [ ! -e "$KIRO_CLI_INSTALL_MARKER" ] \
  && ok "rollback removes components that were absent before a repair install" \
  || no "rollback tombstone" \
    "a promoted component survived the rollback: chat=$([ -e "$CHAT_SIDECAR" ] && echo present || echo gone) marker=$([ -e "$KIRO_CLI_INSTALL_MARKER" ] && echo present || echo gone)"

# ...and it leaves no tombstone behind: an orphaned one would make the NEXT boot's
# recovery pass delete a component that by then belongs to a committed install.
[ ! -e "$BIN_PREV.absent" ] && [ ! -e "$CHAT_SIDECAR_PREV.absent" ] \
  && [ ! -e "$KIRO_CLI_INSTALL_MARKER_PREV.absent" ] \
  && ok "rollback drops the .absent tombstones along with the backups" \
  || no "tombstone cleanup" "a tombstone survived and would delete a committed component next boot"

# The next boot's repair pass, on the state a SIGKILL leaves: journal open, sidecar
# already new, $BIN still old. Without it the drift check reads an old --version off
# a mixed set and the fallback publishes readiness over a terminal that cannot chat.
plant_old_set
kiro_cli_update_begin >/dev/null 2>&1
promote "$CHAT_SIDECAR" new-chat
recover_kiro_cli_update_journal >/dev/null 2>&1
[ "$(cat "$CHAT_SIDECAR")" = "old-chat" ] && [ ! -e "$KIRO_CLI_UPDATE_JOURNAL" ] \
  && ok "boot recovery repairs an uncommitted update before any version check" \
  || no "boot recovery" "the mixed set survived into the boot path"

# A committed update must NOT be rolled back on the next boot, and its backups must
# not keep occupying the volume.
plant_old_set
kiro_cli_update_begin >/dev/null 2>&1
promote "$CHAT_SIDECAR" new-chat
promote "$BIN" new-bin
kiro_cli_update_finish >/dev/null 2>&1
recover_kiro_cli_update_journal >/dev/null 2>&1
[ "$(cat "$BIN")" = "new-bin" ] && [ "$(cat "$CHAT_SIDECAR")" = "new-chat" ] \
  && [ ! -e "$BIN_PREV" ] \
  && ok "a committed update survives the next boot's recovery pass" \
  || no "commit" "recovery reverted or leaked a committed install"

# Recovery is strictly additive: with no journal it must not touch the live set even
# when a stray backup is lying around (a commit whose backup removal failed).
plant_old_set
printf 'stale\n' >"$BIN_PREV"
recover_kiro_cli_update_journal >/dev/null 2>&1
[ "$(cat "$BIN")" = "old-bin" ] && [ ! -e "$BIN_PREV" ] \
  && ok "recovery ignores a stray backup with no journal and sweeps it" \
  || no "stray backup" "recovery restored a backup outside a transaction"

report
