#!/usr/bin/env bash
# The kiro-cli update transaction: download and verify BEFORE deleting anything,
# and if the update fails, keep serving the version already on the volume.
#
# This is the app's availability trade, made deliberately: this container IS the
# operator's access path, so a working old terminal beats a dead one, and the pin
# is advisory while an update keeps failing. That makes the fallback's exact shape
# load-bearing — readiness must still be published, with a warn naming pinned vs
# running, and it must be WITHHELD in the one case where the terminal would be
# unsafe rather than merely stale (auto-update could not be disabled, so the binary
# could silently replace itself and invalidate the pinned sha).
#
# Extracts the two helpers whose return codes the decision reads, plus the real
# readiness chain, and drives them with stubs for the two things that would
# otherwise spawn a process or touch the host.
# Lint directives for this whole file, each against a stated guarantee rather than
# an assumption:
#   SC2015 - the assertion form `[ cond ] && ok "..." || no "..."` cannot mis-fire,
#     because lib.sh's ok/no return 0 unconditionally by design (see their comment).
#   SC2034 - the variables set below are the INPUTS to entrypoint.sh code that is
#     extracted and sourced at RUNTIME, so shellcheck cannot see the reads.
#   SC1091 - the sourced files are GENERATED by the extraction above, so there is
#     nothing on disk for shellcheck to follow at lint time.
# shellcheck disable=SC2015,SC2034,SC1091
set -u

# shellcheck source-path=SCRIPTDIR
. "$(dirname -- "$0")/lib.sh"
new_workdir >/dev/null

# The two helpers whose return codes the fix depends on, concatenated into one
# sourceable file.
HELPERS="$WORK/helpers.sh"
extract_function kiro_cli_dispatcher_set_complete "$HELPERS" >/dev/null
extract_function resolves_to_pinned_kiro_cli "$WORK/_resolve.sh" >/dev/null
cat "$WORK/_resolve.sh" >>"$HELPERS"
# The readiness decision chain is inline boot code, not a function: take it from
# the version probe down to the line before the next section, then drop that line.
READINESS=$(extract_range '^kiro_cli_installed=""' '^# OS packages' "$WORK/readiness.raw")
sed '$d' "$READINESS" >"$WORK/readiness.sh"

# --- scenario scaffolding -----------------------------------------------------
# Each scenario gets a fresh fake volume. Stubs stand in for the two things that
# would otherwise spawn processes or touch the host: the shape test and --version.
setup() {
  ROOT=$(mktemp -d "$WORK/vol.XXXXXX")
  TOOLS="$ROOT/tools"
  HOME="$ROOT/home"
  mkdir -p "$TOOLS/bin" "$HOME/.local/bin"
  BIN="$TOOLS/bin/kiro-cli"
  CHAT_SIDECAR="$TOOLS/bin/kiro-cli-chat"
  KIRO_CLI_INSTALL_MARKER="$TOOLS/.kiro-cli-installed"
  KIRO_CLI_READY_MARKER="$TOOLS/.kiro-cli-ready"
  KIRO_CLI_VERSION="2.14.1"
  SESSION_PATH="$TOOLS/bin:$HOME/.local/bin:/usr/bin"
  kiro_cli_pin_enforced=1
  kiro_cli_update_failed=0
  STUB_VERSION=""
  FATALS=""
}
is_self_contained_executable() { [ -f "$1" ] && [ ! -L "$1" ] && [ -x "$1" ]; }
kiro_cli_version() {
  [ -n "$STUB_VERSION" ] || return 1
  printf '%s\n' "$STUB_VERSION"
}
fatal() { FATALS="$FATALS|$1"; }

run_readiness() { (. "$WORK/readiness.sh" >/dev/null 2>&1); }
ready_published() {
  rm -f "$KIRO_CLI_READY_MARKER"
  # shellcheck disable=SC1090  # extracted chain, path is computed
  . "$WORK/readiness.sh" >/dev/null 2>&1
  [ -f "$KIRO_CLI_READY_MARKER" ]
}

# shellcheck disable=SC1090
. "$WORK/helpers.sh"

# --- 1. dispatcher_set_complete return-code contract -------------------------
setup
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
printf '%s\n' "$KIRO_CLI_VERSION" >"$KIRO_CLI_INSTALL_MARKER"
kiro_cli_dispatcher_set_complete >/dev/null 2>&1
[ $? -eq 0 ] && ok "set_complete rc0 when sidecar ok + marker at pin" \
  || no "set_complete rc0" "expected 0"

setup
mkdir -p "$TOOLS/bin"
printf '%s\n' "$KIRO_CLI_VERSION" >"$KIRO_CLI_INSTALL_MARKER"
kiro_cli_dispatcher_set_complete >/dev/null 2>&1
[ $? -eq 1 ] && ok "set_complete rc1 when the chat sidecar is missing (terminal broken)" \
  || no "set_complete rc1" "expected 1, got $?"

setup
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
kiro_cli_dispatcher_set_complete >/dev/null 2>&1
[ $? -eq 2 ] && ok "set_complete rc2 when the marker is absent (pre-marker volume)" \
  || no "set_complete rc2 absent marker" "expected 2"

setup
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
printf '2.13.0\n' >"$KIRO_CLI_INSTALL_MARKER"
kiro_cli_dispatcher_set_complete >/dev/null 2>&1
[ $? -eq 2 ] && ok "set_complete rc2 when the marker names an older pin" \
  || no "set_complete rc2 old marker" "expected 2"

# --- 2. resolves_to_pinned_kiro_cli return-code contract ---------------------
setup
: >"$BIN" && chmod +x "$BIN"
STUB_VERSION="$KIRO_CLI_VERSION"
resolves_to_pinned_kiro_cli >/dev/null 2>&1
[ $? -eq 0 ] && ok "resolves rc0 when \$BIN is at the pin" || no "resolves rc0" "expected 0"

setup
: >"$BIN" && chmod +x "$BIN"
STUB_VERSION="2.13.0"
resolves_to_pinned_kiro_cli >/dev/null 2>&1
[ $? -eq 2 ] && ok "resolves rc2 when \$BIN holds an older version (the fallback state)" \
  || no "resolves rc2" "expected 2 -- the failed-update fallback would abort boot"

setup
: >"$HOME/.local/bin/kiro-cli" && chmod +x "$HOME/.local/bin/kiro-cli"
SESSION_PATH="$HOME/.local/bin:$TOOLS/bin:/usr/bin"
STUB_VERSION="2.13.0"
resolves_to_pinned_kiro_cli >/dev/null 2>&1
[ $? -eq 1 ] && ok "resolves rc1 when an unpinned copy elsewhere shadows \$BIN" \
  || no "resolves rc1" "expected 1 -- real shadowing must stay fatal"

setup
resolves_to_pinned_kiro_cli >/dev/null 2>&1
[ $? -eq 0 ] && ok "resolves rc0 when nothing is reachable at all" || no "resolves nothing" "expected 0"

# --- 3. readiness decision under each boot outcome --------------------------
# Happy path: install succeeded, everything at the pin.
setup
: >"$BIN" && chmod +x "$BIN"
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
printf '%s\n' "$KIRO_CLI_VERSION" >"$KIRO_CLI_INSTALL_MARKER"
STUB_VERSION="$KIRO_CLI_VERSION"
ready_published && ok "readiness PUBLISHED on a clean install" || no "clean install" "marker withheld"

# Failed update, older version still installed -> serve it.
setup
: >"$BIN" && chmod +x "$BIN"
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
printf '2.13.0\n' >"$KIRO_CLI_INSTALL_MARKER"
STUB_VERSION="2.13.0"
kiro_cli_update_failed=1
ready_published && ok "readiness PUBLISHED on a failed update with the old version present" \
  || no "failed update fallback" "marker withheld -- container would 503 over a working terminal"

# Failed update, nothing installed -> withhold.
setup
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
STUB_VERSION=""
kiro_cli_update_failed=1
ready_published && no "failed install, no binary" "marker published over a dead terminal" \
  || ok "readiness WITHHELD on a failed install with no binary at all"

# Pre-marker volume already at the pin, update failed -> serve it.
setup
: >"$BIN" && chmod +x "$BIN"
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
STUB_VERSION="$KIRO_CLI_VERSION"
kiro_cli_update_failed=1
ready_published && ok "readiness PUBLISHED on a pre-marker volume at the pin after a failed update" \
  || no "pre-marker volume" "marker withheld -- the exact regression this fix targets"

# Failed update, chat sidecar unusable -> withhold even though update_failed is set.
setup
: >"$BIN" && chmod +x "$BIN"
printf '%s\n' "$KIRO_CLI_VERSION" >"$KIRO_CLI_INSTALL_MARKER"
STUB_VERSION="$KIRO_CLI_VERSION"
kiro_cli_update_failed=1
ready_published && no "failed update, sidecar missing" "marker published but kiro-cli chat cannot dispatch" \
  || ok "readiness WITHHELD when the chat sidecar is unusable, fallback or not"

# Auto-update could not be disabled -> withhold (unchanged behaviour).
setup
: >"$BIN" && chmod +x "$BIN"
: >"$CHAT_SIDECAR" && chmod +x "$CHAT_SIDECAR"
printf '%s\n' "$KIRO_CLI_VERSION" >"$KIRO_CLI_INSTALL_MARKER"
STUB_VERSION="$KIRO_CLI_VERSION"
kiro_cli_pin_enforced=0
ready_published && no "pin not enforced" "marker published though the binary may self-replace" \
  || ok "readiness WITHHELD when auto-update could not be disabled"

report
